# Generated by Django 4.2.7 on 2023-11-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=100)),
                ("selling_price", models.FloatField()),
                ("discounted_price", models.FloatField()),
                ("Description", models.TextField()),
                ("composition", models.TextField(default="")),
                ("prodapp", models.TextField(default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("toys", "toys"),
                            ("manga", "manga"),
                            ("costumes", "costumes"),
                            ("posters", "posters"),
                        ],
                        max_length=10,
                    ),
                ),
                ("prodimg", models.ImageField(upload_to="product")),
            ],
        ),
    ]
