# Generated by Django 4.2.7 on 2023-11-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Frontend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="composition",
        ),
        migrations.RemoveField(
            model_name="product",
            name="prodapp",
        ),
    ]
