# Generated by Django 4.2.7 on 2023-11-26 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Frontend", "0003_cart"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="quanity",
            new_name="quantity",
        ),
    ]
