# Generated by Django 4.2.7 on 2023-12-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Frontend", "0004_rename_quanity_cart_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
