# Generated by Django 4.2.7 on 2023-12-12 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Frontend", "0005_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Frontend.product",
                unique=True,
            ),
        ),
    ]
