# Generated by Django 4.2.7 on 2023-12-13 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Frontend", "0008_orders"),
    ]

    operations = [
        migrations.RenameModel(old_name="Orders", new_name="Order",),
    ]
